### ISSUE TITLE
Cool👍

### ISSUE THREAD

**Issue by AliSheyx-life** [AndyMagwayer/Imatating-html#1]
Kamida 5 ta commit bo'lishi kerak edi
![commit bug](https://user-images.githubusercontent.com/68541818/236537237-52b68da9-a8d2-4b57-bf7d-abe73d3f4f18.png)

**Comment by AliSheyx-life** [comment]
Site ga kirish uchun ssilka qilib tashamagansiz

**Comment by AndyMagwayer** [comment]
Я не смог найти ссылку ,ссылка не вышла просто Алишер Ака (но в группу я видео скинул )
